<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Tools" Version="2.72.0" PrivateAssets="All" />
        <PackageReference Include="Grpc.Core.Api" Version="2.71.0" />
        <PackageReference Include="Google.Protobuf" Version="3.32.1" />
    </ItemGroup>

    <ItemGroup>
        <!-- Generate both client & server stubs in this assembly -->
        <Protobuf Include="proto\catalog.proto" GrpcServices="Server,Client" />
        <Protobuf Include="proto\orders.proto" GrpcServices="Server,Client" />
    </ItemGroup>
</Project>